// <auto-generated />
namespace BanHang.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
<<<<<<<< HEAD:BanHang/Migrations/202311121103410_repair.Designer.cs
    public sealed partial class repair : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(repair));
        
        string IMigrationMetadata.Id
        {
            get { return "202311121103410_repair"; }
========
    public sealed partial class update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update));
        
        string IMigrationMetadata.Id
        {
            get { return "202311070604025_update"; }
>>>>>>>> master:BanHang/Migrations/202311070604025_update.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
