// <auto-generated />
namespace BanHang.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Remove2UselessClasses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Remove2UselessClasses));
        
        string IMigrationMetadata.Id
        {
            get { return "202305310817598_Remove2UselessClasses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
