// <auto-generated />
namespace BanHang.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class tuanfixing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tuanfixing));
        
        string IMigrationMetadata.Id
        {
            get { return "202306110936157_tuanfixing"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
